'use client';

import Link from 'next/link';
import { useLocale } from 'next-intl';
import CtaButton from '@/components/CtaButton';
import Breadcrumbs from '@/components/Breadcrumbs';

export default function OtcTradingBinaryOptionsPage() {
  const locale = useLocale();

  return (
    <article className="section-container py-16 max-w-4xl mx-auto">
      <Breadcrumbs items={[{ label: 'Blog', href: `/${locale}/blog` }, { label: 'OTC Trading Guide' }]} />
      <header className="mb-12">
        <div className="flex items-center gap-2 mb-4">
          <span className="badge-blue">Trading Guide</span>
          <span className="text-xs text-gray-600">Updated May 2026 • 12 min read</span>
        </div>
        <h1 className="text-3xl md:text-4xl font-extrabold mb-4 leading-tight">
          OTC Trading in Binary Options — Weekend Trading Guide 2026
        </h1>
        <p className="text-lg text-gray-400 leading-relaxed">
          Want to trade binary options on weekends? OTC (Over-the-Counter) markets make it possible.
          This guide covers how OTC trading works, which brokers offer it, and strategies to navigate
          these unique markets.
        </p>
      </header>

      {/* What Is OTC Trading */}
      <section className="glass-card p-6 mb-10">
        <h2 className="text-lg font-bold mb-3 text-blue-400">What Is OTC Trading in Binary Options?</h2>
        <p className="text-gray-300 text-sm leading-relaxed mb-4">
          OTC (Over-the-Counter) trading refers to assets that are <strong className="text-white">traded directly between the broker
          and the trader</strong>, rather than through a centralized exchange. In the binary options context, OTC assets
          are synthetic instruments created by the broker that mimic real market movements but are available
          <strong className="text-white"> 24/7, including weekends and holidays</strong>.
        </p>
        <div className="grid sm:grid-cols-3 gap-4">
          <div className="bg-white/[0.03] rounded-lg p-3 text-center">
            <div className="text-lg font-bold text-white">24/7</div>
            <div className="text-xs text-gray-400">Available around the clock</div>
          </div>
          <div className="bg-white/[0.03] rounded-lg p-3 text-center">
            <div className="text-lg font-bold text-white">Weekends</div>
            <div className="text-xs text-gray-400">Trade Saturday & Sunday</div>
          </div>
          <div className="bg-white/[0.03] rounded-lg p-3 text-center">
            <div className="text-lg font-bold text-white">Broker-Set</div>
            <div className="text-xs text-gray-400">Prices set by broker</div>
          </div>
        </div>
      </section>

      {/* How OTC Markets Work */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-6">How OTC Markets Work</h2>
        <p className="text-gray-400 text-sm mb-6">
          Understanding the mechanics of OTC trading is crucial before you start. Here&apos;s what happens behind the scenes:
        </p>
        <div className="space-y-4">
          {[
            { title: 'Price Generation', desc: 'Unlike regular assets where prices come from exchanges (NYSE, NASDAQ, forex interbank), OTC prices are generated by the broker\'s algorithm. They use historical patterns, volatility models, and random walks to create price movements.' },
            { title: 'No External Market', desc: 'When you trade EUR/USD OTC on a weekend, you\'re not trading against the actual forex market (which is closed). You\'re trading against the broker\'s synthetic price feed. This is a fundamental difference from weekday trading.' },
            { title: 'Counterparty Risk', desc: 'In OTC trading, the broker is your counterparty — when you win, the broker pays you. When you lose, the broker keeps your stake. This creates a potential conflict of interest that you should be aware of.' },
            { title: 'Availability', desc: 'OTC assets appear in your broker\'s asset list alongside regular assets. They\'re typically labeled with "OTC" suffix (e.g., "EUR/USD OTC") and are only available when the corresponding real market is closed.' },
          ].map((item) => (
            <div key={item.title} className="glass-card p-5">
              <h3 className="font-semibold text-white text-sm mb-2">{item.title}</h3>
              <p className="text-sm text-gray-400">{item.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* OTC vs Regular Trading */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-6">OTC vs Regular Market Trading</h2>
        <div className="glass-card overflow-hidden">
          <div className="grid grid-cols-3 bg-white/[0.03] border-b border-white/[0.06] p-3 text-xs font-semibold text-gray-400">
            <div>Factor</div>
            <div className="text-center">OTC Markets</div>
            <div className="text-center">Regular Markets</div>
          </div>
          {[
            { factor: 'Availability', otc: '24/7 including weekends', regular: 'Market hours only (Mon-Fri)' },
            { factor: 'Price Source', otc: 'Broker algorithm', regular: 'Exchange/interbank rates' },
            { factor: 'Transparency', otc: 'Lower — broker controls prices', regular: 'Higher — public market data' },
            { factor: 'Technical Analysis', otc: 'Less reliable', regular: 'Standard TA applies' },
            { factor: 'Payouts', otc: 'Often lower (70-85%)', regular: 'Standard (80-95%)' },
            { factor: 'Volatility', otc: 'Controlled, moderate', regular: 'Natural market volatility' },
            { factor: 'News Impact', otc: 'None — synthetic prices', regular: 'Full impact from events' },
            { factor: 'Best For', otc: 'Weekend trading, practice', regular: 'Serious trading, analysis' },
          ].map((row, i) => (
            <div key={i} className={`grid grid-cols-3 p-3 text-sm ${i % 2 ? 'bg-white/[0.01]' : ''} border-b border-white/[0.03]`}>
              <div className="text-white font-medium">{row.factor}</div>
              <div className="text-center text-blue-400">{row.otc}</div>
              <div className="text-center text-gray-400">{row.regular}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Which Brokers Offer OTC */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-6">Which Brokers Offer OTC Trading?</h2>
        <p className="text-gray-400 text-sm mb-6">
          Not all binary options brokers provide OTC markets. Here are the ones that do and how they compare:
        </p>
        <div className="space-y-4">
          {/* Pocket Option */}
          <div className="glass-card p-6 border border-emerald-500/20">
            <div className="flex items-center gap-3 mb-3">
              <h3 className="text-lg font-bold text-white">Pocket Option — Best OTC Selection</h3>
              <span className="text-xs bg-emerald-500/20 text-emerald-400 px-2 py-0.5 rounded-full">Recommended</span>
            </div>
            <p className="text-sm text-gray-300 mb-3">
              Pocket Option offers the widest selection of OTC assets among binary options brokers. You&apos;ll find
              OTC versions of major forex pairs, cryptocurrencies, and some commodities. Available whenever the
              corresponding real market is closed.
            </p>
            <div className="grid sm:grid-cols-3 gap-3 mb-3">
              <div className="bg-white/[0.03] rounded-lg p-2 text-center">
                <div className="text-xs text-gray-400">OTC Assets</div>
                <div className="text-sm font-bold text-emerald-400">30+ pairs</div>
              </div>
              <div className="bg-white/[0.03] rounded-lg p-2 text-center">
                <div className="text-xs text-gray-400">OTC Payouts</div>
                <div className="text-sm font-bold text-white">75-85%</div>
              </div>
              <div className="bg-white/[0.03] rounded-lg p-2 text-center">
                <div className="text-xs text-gray-400">Weekend</div>
                <div className="text-sm font-bold text-emerald-400">Available</div>
              </div>
            </div>
            <Link href={`/${locale}/pocket-option`} className="text-blue-400 text-sm hover:underline">
              Read full Pocket Option review →
            </Link>
          </div>

          {/* Olymp Trade */}
          <div className="glass-card p-6">
            <div className="flex items-center gap-3 mb-3">
              <h3 className="text-lg font-bold text-white">Olymp Trade — OTC with Education</h3>
              <span className="text-xs bg-blue-500/20 text-blue-400 px-2 py-0.5 rounded-full">Good Option</span>
            </div>
            <p className="text-sm text-gray-300 mb-3">
              Olymp Trade provides OTC assets with educational resources explaining how they differ from
              regular markets. Their OTC selection is smaller than Pocket Option but the trading experience
              is smooth with clear labeling of OTC assets.
            </p>
            <div className="grid sm:grid-cols-3 gap-3 mb-3">
              <div className="bg-white/[0.03] rounded-lg p-2 text-center">
                <div className="text-xs text-gray-400">OTC Assets</div>
                <div className="text-sm font-bold text-blue-400">15+ pairs</div>
              </div>
              <div className="bg-white/[0.03] rounded-lg p-2 text-center">
                <div className="text-xs text-gray-400">OTC Payouts</div>
                <div className="text-sm font-bold text-white">70-82%</div>
              </div>
              <div className="bg-white/[0.03] rounded-lg p-2 text-center">
                <div className="text-xs text-gray-400">Weekend</div>
                <div className="text-sm font-bold text-emerald-400">Available</div>
              </div>
            </div>
            <Link href={`/${locale}/olymp-trade`} className="text-blue-400 text-sm hover:underline">
              Read full Olymp Trade review →
            </Link>
          </div>

          {/* Deriv */}
          <div className="glass-card p-6">
            <div className="flex items-center gap-3 mb-3">
              <h3 className="text-lg font-bold text-white">Deriv — Synthetic Indices (Different Approach)</h3>
              <span className="text-xs bg-purple-500/20 text-purple-400 px-2 py-0.5 rounded-full">Alternative</span>
            </div>
            <p className="text-sm text-gray-300 mb-3">
              Deriv doesn&apos;t offer traditional OTC binary options, but their synthetic indices serve a similar
              purpose — 24/7 trading on algorithmically generated markets. These include Volatility indices,
              Crash/Boom, Step indices, and more. They&apos;re regulated and audited for fairness.
            </p>
            <div className="grid sm:grid-cols-3 gap-3 mb-3">
              <div className="bg-white/[0.03] rounded-lg p-2 text-center">
                <div className="text-xs text-gray-400">Synthetic Types</div>
                <div className="text-sm font-bold text-purple-400">20+ indices</div>
              </div>
              <div className="bg-white/[0.03] rounded-lg p-2 text-center">
                <div className="text-xs text-gray-400">Availability</div>
                <div className="text-sm font-bold text-white">True 24/7</div>
              </div>
              <div className="bg-white/[0.03] rounded-lg p-2 text-center">
                <div className="text-xs text-gray-400">Regulation</div>
                <div className="text-sm font-bold text-emerald-400">MFSA, VFSC</div>
              </div>
            </div>
            <Link href={`/${locale}/deriv`} className="text-blue-400 text-sm hover:underline">
              Read full Deriv review →
            </Link>
            {' | '}
            <Link href={`/${locale}/blog/deriv-synthetic-indices-guide`} className="text-blue-400 text-sm hover:underline">
              Deriv Synthetic Indices Guide →
            </Link>
          </div>
        </div>
      </section>

      {/* Pros and Cons */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-6">Pros and Cons of OTC Trading</h2>
        <div className="grid sm:grid-cols-2 gap-6">
          <div className="glass-card p-6 border border-emerald-500/20">
            <h3 className="text-lg font-bold text-emerald-400 mb-4">Advantages</h3>
            <ul className="space-y-3 text-sm text-gray-300">
              <li className="flex gap-2">
                <span className="text-emerald-400 flex-shrink-0">+</span>
                <span><strong className="text-white">Weekend trading:</strong> Don&apos;t have to wait for Monday to trade. Perfect for people with weekday jobs.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-emerald-400 flex-shrink-0">+</span>
                <span><strong className="text-white">24/7 availability:</strong> Trade any time — holidays, late nights, whenever suits your schedule.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-emerald-400 flex-shrink-0">+</span>
                <span><strong className="text-white">Practice opportunities:</strong> Great for practicing strategies when real markets are closed.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-emerald-400 flex-shrink-0">+</span>
                <span><strong className="text-white">Lower volatility:</strong> OTC prices tend to be smoother, which some strategies work better on.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-emerald-400 flex-shrink-0">+</span>
                <span><strong className="text-white">No news spikes:</strong> No surprise gaps from economic news releases or geopolitical events.</span>
              </li>
            </ul>
          </div>

          <div className="glass-card p-6 border border-red-500/20">
            <h3 className="text-lg font-bold text-red-400 mb-4">Disadvantages</h3>
            <ul className="space-y-3 text-sm text-gray-300">
              <li className="flex gap-2">
                <span className="text-red-400 flex-shrink-0">-</span>
                <span><strong className="text-white">Broker controls prices:</strong> The broker generates OTC prices — potential conflict of interest.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-red-400 flex-shrink-0">-</span>
                <span><strong className="text-white">Lower payouts:</strong> OTC payouts are typically 5-15% lower than regular market payouts.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-red-400 flex-shrink-0">-</span>
                <span><strong className="text-white">Limited TA effectiveness:</strong> Technical analysis is less reliable on synthetic price data.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-red-400 flex-shrink-0">-</span>
                <span><strong className="text-white">No fundamental analysis:</strong> News and events don&apos;t affect OTC prices, removing one analysis tool.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-red-400 flex-shrink-0">-</span>
                <span><strong className="text-white">Less transparency:</strong> No way to verify OTC prices against external data sources.</span>
              </li>
            </ul>
          </div>
        </div>
      </section>

      {/* OTC Trading Strategies */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-6">Strategies for OTC Trading</h2>
        <p className="text-gray-400 text-sm mb-6">
          OTC markets behave differently from regular markets, so you need adapted strategies. Here are
          approaches that work better on OTC:
        </p>
        <div className="space-y-4">
          <div className="glass-card p-6">
            <h3 className="text-base font-bold text-white mb-3">1. Support/Resistance with Range Trading</h3>
            <p className="text-sm text-gray-300 mb-3">
              OTC prices tend to oscillate within defined ranges rather than trending strongly. Identify
              support and resistance levels on the chart, then trade bounces off these levels. This works
              because broker algorithms often create mean-reverting price action.
            </p>
            <div className="bg-white/[0.03] rounded-lg p-3">
              <p className="text-xs text-gray-400">
                <strong className="text-amber-300">Tip:</strong> Use 5-15 minute expiries for range trades.
                Shorter expiries are too noisy; longer ones may see the range break.
              </p>
            </div>
          </div>

          <div className="glass-card p-6">
            <h3 className="text-base font-bold text-white mb-3">2. Candlestick Patterns on Higher Timeframes</h3>
            <p className="text-sm text-gray-300 mb-3">
              While 1-minute candles on OTC are noisy, 5-minute and 15-minute candle patterns can still be
              meaningful. Look for reversal patterns (pin bars, engulfing candles, doji) at support/resistance
              levels for higher-probability entries.
            </p>
            <div className="bg-white/[0.03] rounded-lg p-3">
              <p className="text-xs text-gray-400">
                <strong className="text-amber-300">Tip:</strong> Confirm patterns with at least one indicator
                (RSI or Bollinger Bands). Don&apos;t trade candlestick patterns alone on OTC.
              </p>
            </div>
          </div>

          <div className="glass-card p-6">
            <h3 className="text-base font-bold text-white mb-3">3. Bollinger Band Bounces</h3>
            <p className="text-sm text-gray-300 mb-3">
              Bollinger Bands work relatively well on OTC because the price tends to stay within defined
              volatility bands. When price touches the upper band, look for PUT opportunities. When it
              touches the lower band, look for CALL opportunities. This is a classic mean-reversion strategy.
            </p>
            <div className="bg-white/[0.03] rounded-lg p-3">
              <p className="text-xs text-gray-400">
                <strong className="text-amber-300">Tip:</strong> Use standard settings (20 period, 2 standard deviations).
                Wait for the candle to close outside the band before entering — don&apos;t rush.
              </p>
            </div>
          </div>

          <div className="glass-card p-6">
            <h3 className="text-base font-bold text-white mb-3">4. Small Stakes, High Volume</h3>
            <p className="text-sm text-gray-300 mb-3">
              Since OTC is inherently less predictable, reduce your trade size and increase your number of
              trades. Instead of 5 trades at $10 each, consider 20 trades at $2 each. This smooths out
              the randomness and gives your strategy more room to show its edge.
            </p>
            <div className="bg-white/[0.03] rounded-lg p-3">
              <p className="text-xs text-gray-400">
                <strong className="text-amber-300">Tip:</strong> Never risk more than 2% of your balance per OTC trade.
                The reduced predictability means you need stricter money management.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* What to Avoid */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-6">What to Avoid in OTC Trading</h2>
        <div className="border border-red-500/30 bg-red-500/[0.03] rounded-xl p-6">
          <div className="space-y-4">
            {[
              { mistake: 'Using Complex Indicators', detail: 'Indicators like MACD, Ichimoku, and moving average crossovers are designed for real market data with genuine trends. On OTC\'s synthetic data, they generate false signals frequently.' },
              { mistake: 'Martingale Strategy', detail: 'Doubling down after losses is dangerous on any market, but especially on OTC where you can\'t verify the fairness of price movements. A losing streak on OTC could be longer than expected.' },
              { mistake: 'Large Trade Sizes', detail: 'Never use the same trade sizes on OTC that you\'d use on regular markets. The lower predictability means you need smaller stakes to survive drawdowns.' },
              { mistake: 'Treating OTC Like Real Markets', detail: 'The biggest mistake is assuming OTC behaves exactly like the real EUR/USD or BTC/USD. It doesn\'t. Different rules apply.' },
              { mistake: 'Trading When Bored', detail: 'Many traders jump into OTC on weekends just because markets are open. If you don\'t have a clear strategy for OTC, don\'t trade — you\'re gambling.' },
            ].map((item) => (
              <div key={item.mistake} className="flex gap-3">
                <span className="text-red-400 text-sm mt-0.5 flex-shrink-0">✗</span>
                <div>
                  <span className="text-white font-medium text-sm">{item.mistake}</span>
                  <p className="text-gray-400 text-sm">{item.detail}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-6">Frequently Asked Questions</h2>
        <div className="space-y-4">
          {[
            { q: 'Is OTC trading rigged?', a: 'OTC prices are broker-generated, which raises fairness questions. Reputable brokers use audited algorithms, but there\'s no independent exchange to verify prices against. Trade with established brokers and keep stakes small.' },
            { q: 'Can I make money trading OTC?', a: 'Yes, but it\'s harder than regular market trading. Lower payouts and synthetic prices mean your win rate needs to be higher to be profitable. Expect lower returns than regular trading.' },
            { q: 'What are OTC trading hours?', a: 'OTC assets are typically available when the corresponding real market is closed. For forex OTC, that\'s Saturday morning through Sunday evening. Some brokers offer OTC during weekday off-hours too.' },
            { q: 'Does technical analysis work on OTC?', a: 'Basic TA (support/resistance, Bollinger Bands, RSI) works to some extent because broker algorithms create recognizable patterns. Complex strategies (Elliott Wave, Fibonacci extensions) are less reliable.' },
            { q: 'Are OTC payouts lower?', a: 'Yes, typically 5-15% lower than regular market payouts. For example, if EUR/USD regular payout is 90%, the EUR/USD OTC payout might be 75-82%.' },
            { q: 'Is OTC the same as synthetic indices?', a: 'Similar concept but different execution. OTC assets mimic real assets (EUR/USD OTC). Synthetic indices (like Deriv\'s Volatility 75) are unique instruments with their own behavior. Both are broker-generated.' },
          ].map((faq) => (
            <div key={faq.q} className="glass-card p-5">
              <h3 className="font-semibold text-white text-sm mb-2">{faq.q}</h3>
              <p className="text-sm text-gray-400">{faq.a}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Related Articles */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-4">Related Articles</h2>
        <div className="grid sm:grid-cols-2 gap-4">
          <Link href={`/${locale}/blog/deriv-synthetic-indices-guide`} className="glass-card p-4 hover:border-blue-500/30 transition-colors">
            <h3 className="text-sm font-semibold text-white mb-1">Deriv Synthetic Indices Guide</h3>
            <p className="text-xs text-gray-400">The regulated alternative to OTC — trade 24/7 on audited synthetic markets.</p>
          </Link>
          <Link href={`/${locale}/blog/binary-options-copy-trading`} className="glass-card p-4 hover:border-blue-500/30 transition-colors">
            <h3 className="text-sm font-semibold text-white mb-1">Binary Options Copy Trading Guide</h3>
            <p className="text-xs text-gray-400">Skip the analysis — copy top traders automatically on Pocket Option.</p>
          </Link>
          <Link href={`/${locale}/blog/binary-options-mobile-trading`} className="glass-card p-4 hover:border-blue-500/30 transition-colors">
            <h3 className="text-sm font-semibold text-white mb-1">Best Binary Options Mobile Apps 2026</h3>
            <p className="text-xs text-gray-400">Trade OTC markets from your phone — which apps support weekend trading?</p>
          </Link>
          <Link href={`/${locale}/blog/pocket-option-withdrawal`} className="glass-card p-4 hover:border-blue-500/30 transition-colors">
            <h3 className="text-sm font-semibold text-white mb-1">Pocket Option Withdrawal Guide</h3>
            <p className="text-xs text-gray-400">How to withdraw your OTC trading profits from Pocket Option.</p>
          </Link>
        </div>
      </section>

      {/* CTA */}
      <section className="glass-card p-8 text-center mb-10">
        <h2 className="text-2xl font-bold mb-3">Try OTC Trading This Weekend</h2>
        <p className="text-gray-400 mb-6 text-sm max-w-lg mx-auto">
          Test OTC markets on Pocket Option&apos;s demo account — $50,000 virtual balance, available 24/7.
          Practice your OTC strategies with zero risk before going live.
        </p>
        <div className="flex flex-col sm:flex-row gap-3 justify-center">
          <CtaButton broker="pocketOption" type="demo" label="Try OTC Trading (Demo)" campaign="blog_otc" />
          <CtaButton broker="pocketOption" label="Open Real Account ($5)" variant="secondary" campaign="blog_otc" />
        </div>
      </section>

      {/* Risk Disclaimer */}
      <section className="border border-gray-700/50 rounded-xl p-5">
        <p className="text-xs text-gray-500 leading-relaxed">
          <strong className="text-gray-400">Risk Disclaimer:</strong> Binary options trading involves substantial risk of loss and is not suitable
          for all investors. OTC markets carry additional risks as prices are generated by the broker rather than derived from external exchanges.
          You could lose some or all of your invested capital. Only trade with money you can afford to lose. This content is for educational
          purposes only and does not constitute financial advice. Past performance is not indicative of future results.
        </p>
      </section>
    </article>
  );
}
